version: '3.8'

services:
  service:
    container_name: ${SERVICE_ID}
    build: .
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongodb
    networks:
      - traefik-network

  mongodb:
    container_name: ${SERVICE_ID}-db
    image: mongo:latest
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - traefik-network

networks:
  traefik-network:
    name: traefik-network

volumes:
  mongodb_data: