version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DB_NAME=project_service
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    depends_on:
      - mongodb
    networks:
      - project-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

volumes:
  mongodb_data: 